### PR TITLE
Update to syn 2

### PR DESCRIPTION
**Pull request by omid**
🚧 🚧 🚧
It's a breaking change!
🚧 🚧 🚧

Because [syn throws an error for keywords](https://github.com/dtolnay/syn/issues/1458), we have to rename `type` to something else. A general pattern is to use `ty` instead of `type`.

### CODE REVIEW

**Comment by omid** [comment]
@jaemk Reminder :D

**Comment by BaxHugh** [comment]
Hey @omid, nice work. Looking at it, it mostly just seems like `type` -> `ty`. I like that you've made the change in places other than just the macro call for consistency.

Only thing I've noticed is that we've now got a few calls of `&String.as_str()` which I think are unnecessary so I've removed them and eveything still works in https://github.com/omid/cached/pull/1 to your branch

**Comment by omid** [comment]
Thanks a lot @BaxHugh. Just merged 🙏🏼

**Comment by jaemk** [comment]
Thanks @omid and @BaxHugh !

**Comment by jaemk** [comment]
FYI, I'm going to wait to release these changes since there's a couple more breaking changes in PR

**Pull request merged**
