### PR TITLE
Initial Draft to fix the case where the DiskCache doesn't persist

### PR DESCRIPTION
**Pull request by BaxHugh**
Initial attempt at providing a resolution to https://github.com/jaemk/cached/issues/190.

I haven't looked at all options, this is just the first solution I saw. I think there's probably some config / setting for sled that should do this for us?

### CODE REVIEW

**Comment by omid** [comment]
As far as I see... `sled automatically fsyncs every 500ms by default`, which looks fine to me.

**Comment by jaemk** [comment]
Thanks @BaxHugh - could you add a flag to the cache type to optionally enable this? Not every use-case requires a hard fsync on every operation. An option would need to be added to the IO macro also

**Comment by BaxHugh** [comment]
Great thanks for the feedback @jaemk and @omid, I'll update with an option to the macro. 
So the [io_cached](https://docs.rs/cached/latest/cached/proc_macro/attr.io_cached.html) macro is generic for any io based cache right?.
This sync to disk on cache_set option currently would only be implemented for the specific DiskCache.
I think the simplest thing to implement would be to add the boolean flag in the io_cache macro args, stating that only some backends (DiskCache)  currently support it, so it may not do anything for other backends.

**Comment by BaxHugh** [comment]
The changes here are now based upon https://github.com/jaemk/cached/pull/193, I can't stage PRs on that one, as the branch is in my clone. But the PR in my clone: https://github.com/BaxHugh/cached/pull/1 shows just the changes relating to this feature

**Pull request closed without merging**
