### PR TITLE
add a proc macro version

### LINKED ISSUE #13: Proc macro based version
Do you have a plan to rebuild the macros based on the [proc_macro](https://github.com/rust-lang/rfcs/blob/master/text/1566-proc-macros.md)?

Those are sweeter.
```rust
#[cached(Fib)]
fn fib(n: u64) -> u64 {
     if n == 0 || n == 1 { 
        return n; 
      }
      fib(n-1) + fib(n-2)
}
```

### LINKED ISSUE #15: macro: `pub fn` is not supported
The macro doesn't let me assign privacy to the function.

```
error: no rules expected the token `pub`
  --> src/...
   |
24 |         pub fn get(a_keyword: &str) -> Option<Self> = {
   |         ^^^
```

### PR DESCRIPTION
**Pull request by csos95**
This fixes #13 and fixes #15.

### CODE REVIEW

**Comment by csos95** [comment]
I just realized that this proc macro doesn't support using a custom cache type.
I'll add more attributes to support this
- [ ] type = "`Type`" - set cache type
- [ ] create = "`Block`" - set cache creation block

Like with the key and convert attributes, it's going to have to be strings that get parsed separately.

**Comment by jaemk** [comment]
This is awesome, thank you!

**Comment by csos95** [comment]
Okay, I got those added. Tomorrow I will add some documentation to the proc macro and then this should be good to go.

**Comment by csos95** [comment]
I added the documentation and since adding proc macros can sometimes increase compile time by quite a bit if there aren't already dependencies using them, I added it as a default feature.
If someone wants to use this without the overhead of compiling syn they can add `default-features = false` to the dependency.

**Comment by jaemk** [comment]
Nice, thanks! I'll upload a new release later today

**Pull request merged**
