### PR TITLE
Add support for async functions to proc macro and async_std/tokio examples

### LINKED ISSUE #30: Is there a way to use cached with an async / await?
I'd like to be able to use cached with an async function and not use block_on. For example:

```rust
cached!{
    MY_ASYNC_MATH;
    async fn(id: i32) -> i32 = {
        let result = some_async_math_call(id).await;
        result
    }
}
```

### PR DESCRIPTION
**Pull request by csos95**
this fixes #30

### CODE REVIEW

**Comment by jaemk** [comment]
on fire today! I'm not super familiar with how async-std and tokio interact. Is async-std's Mutex compatible with tokio's runtime (seems like it is if your example works)?

**Comment by csos95** [comment]
There are some issue with specific structs from async_std/tokio that are difficult to use in the others ecosystem, but luckily the Mutex is not one of them.

**Comment by jaemk** [comment]
nice

**Comment by Acidic9** [comment]
Does this work with `cached_key_result!`? I'm having some issues getting it to work.

**Pull request merged**
