### PR TITLE
WASM support proposal

### PR DESCRIPTION
**Pull request by Altair-Bueno**
### Motivation

Rust is widely used to improve performance on the web using WASM. By adding WASM support to cached, developers may use memorisation to further improve performance on the web

### Proposed changes

- Replace `std::time::Instant` with `instant::Instant` , which is a light wrapper around `std::time::Instant` on native platforms
- Provide a WASM example using the [yew](https://yew.rs/) framework
- Add a `wasm` feature to enable `instant/wasm-bindgen` feature

### Caveats

- New dependency added: https://crates.io/crates/instant
- Test suite requires some minor changes to accommodate for the provided example
- Missing tests for WASM platforms. It is possible to run `wasm-bindgen` tests using node.js, but I'll like to discuss the implementation details after receiving some feedback from the maintainer 

### More information

- Relates to https://github.com/jaemk/cached/pull/31

### CODE REVIEW

**Comment by jaemk** [comment]
Nice! Some questions/comments:

- Definitely will need to update the documentation - at the very least to mention that the `redis` feature is likely incompatible with wasm (not sure if this is true or not, I haven't tried compiling anything to wasm yet)
- For the wasm tests, can we make the `lint-test.sh` script smarter to honor some extra env vars like `INSTALL_MISSING_DEPS` and `SKIP_WASM_TESTS` so that contributors can avoid installing extra dependencies locally, but the PR builds will install and test everything?

**Comment by Altair-Bueno** [comment]
> redis feature is likely incompatible with wasm

Indeed. See https://github.com/redis-rs/redis-rs/issues/508. Apart from updating the documentation, we could add [static_assertions](https://docs.rs/static_assertions/1.1.0/static_assertions/macro.assert_cfg.html) and provide compile-time errors

> contributors can avoid installing extra dependencies locally, but the PR builds will install and test everything?

The wasm example I provided can be compiled using cargo alone, it just won't run without a browser. Nonetheless, proper `wasm_bindgen` tests require more dependencies.

To mitigate this on the contributor side, we could mimic what other build systems like `make` does: a series of goals that can be executed individually or multiple at once

```sh
# Normal unit tests
./lint-tests.sh unit:native
# Fmt tests
./lint-tests.sh fmt
# Multiple tests
./lint-tests.sh fmt integration:redis unit:wasm
# All tests
./lint-tests.sh all
```

This might be a good opportunity to switch the shell script to a dedicated build tool, like `make` or `Scons`. This way, future updates (eg. adding another test suite) would be much easier.

**Comment by Altair-Bueno** [comment]
> Would you be willing to make that change in this or a follow-up PR?

Sure, I'm confident enough on my Makefile skills to pull this off

**Comment by Altair-Bueno** [comment]
PS: Last commit rollbacks some undesired IntelliJ automatic refactoring. I have disabled it now. Sorry for the inconvenience

**Comment by SohumB** [comment]
Hiya! I was testing out this PR, and I noticed that my testcase compiled, but paniced at runtime, due to the use of `std::time::Instant` in `cached_proc_macro/src/lib.rs`.

**Comment by Altair-Bueno** [comment]
Hi @SohumB , that weird. `instant::Instant` it's just a type definition for all platforms (except WASM)

https://github.com/sebcrozet/instant/blob/78e336db632f1f2f7350e2b2385c23d263178251/src/native.rs#L1

Also, I checked the CI log and tests run successfully. The [CI failed](https://github.com/jaemk/cached/runs/6977399991?check_suite_focus=true) because of the WASM example I included, which was expected. macOS passes tests successfully too.

I intentionally left tests unmodified because it's usually not good practice to refactor tests if your changes are allegedly compatible. Nonetheless, I will replace all `std::time` calls with the `instant` crate, just to be safe. If these changes are not welcome, we can just rollback the last commit!

**Comment by Altair-Bueno** [comment]
Latest commit replaces a couple of `std::time` calls I missed inside the `cached_proc_macro` crate with the `instant` crate. Let me know if you find anything else I may have missed

**Comment by SohumB** [comment]
Ah — I don't know if I was clear about this — what I meant to say is that it compiled successfully but panicked at runtime _on wasm_. The compiled code as generated by the macro included the `std::time::Instant` references, and that causes this particular panic at runtime:

```
panicked at 'time not implemented on this platform', library/std/src/sys/wasm/../unsupported/time.rs:13:9

Stack:

Error
    at /home/sohum/versioned/xdi/façades/abc-spec/wasm/pkg/wasm.js:343:21
    at logError (/home/sohum/versioned/xdi/façades/abc-spec/wasm/pkg/wasm.js:218:18)
    at imports.wbg.__wbg_new_693216e109162396 (/home/sohum/versioned/xdi/façades/abc-spec/wasm/pkg/wasm.js:342:66)
    at console_error_panic_hook::Error::new::hb4c85e470cbf45c4 (wasm://wasm/0157e4aa:wasm-function[10694]:0x3dae84)
    at console_error_panic_hook::hook_impl::ha2ba6af2c51bc936 (wasm://wasm/0157e4aa:wasm-function[1525]:0x298c82)
    at console_error_panic_hook::hook::hd0eb0408f10d9336 (wasm://wasm/0157e4aa:wasm-function[11997]:0x3ecbc2)
    at core::ops::function::Fn::call::hb46aadd68e93d122 (wasm://wasm/0157e4aa:wasm-function[9973]:0x3cfc2d)
    at std::panicking::rust_panic_with_hook::h4005aa7bd00d87b4 (wasm://wasm/0157e4aa:wasm-function[3322]:0x31b6e1)
    at std::panicking::begin_panic_handler::{{closure}}::hc6f715784fcf9c56 (wasm://wasm/0157e4aa:wasm-function[4601]:0x350abf)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h5f8d313d7a670ace (wasm://wasm/0157e4aa:wasm-function[13905]:0x3ff44c)
    at rust_begin_unwind (wasm://wasm/0157e4aa:wasm-function[11283]:0x3e34dd)
    at core::panicking::panic_fmt::h68154f52debc3faf (wasm://wasm/0157e4aa:wasm-function[11914]:0x3ebad1)
    at std::time::Instant::now::h7d82ea459f6902dc (wasm://wasm/0157e4aa:wasm-function[11912]:0x3eba50)
    at testcase::cached_function::{{closure}}::ha6fb254999684da7 (wasm://wasm/0157e4aa:wasm-function[210]:0x14d17b)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h317477a0a7cf67cc (wasm://wasm/0157e4aa:wasm-function[984]:0x2553bc)
   ...
```

If it helps you form a better mental model of what's going on, the panic does not occur in my `#[cached]` invocation test case, but it does occur in my `#[once(result, sync_writes)]` invocation test case.

With your new commit (`1ec5750a`), I get a compile failure on wasm.

```
error[E0433]: failed to resolve: use of undeclared crate or module `instant`
  --> ....rs:89:1
   |
89 | #[once(sync_writes, result)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `instant`
   |
   = note: this error originates in the attribute macro `once` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this struct
   |
1  | use std::time::Instant;
   |
help: if you import `Instant`, refer to it directly
   |
89 - #[once(sync_writes, result)]
89 + #[once(sync_writes, result)]
   |

For more information about this error, try `rustc --explain E0433`.
error: could not compile `acrobase` due to previous error
Error: Compiling your crate to WebAssembly failed
Caused by: failed to execute `cargo build`: exited with exit status: 101
  full command: "cargo" "build" "--lib" "--target" "wasm32-unknown-unknown"
```

**Comment by SohumB** [comment]
Ah, yes, that makes sense. Thank you!

**Comment by Altair-Bueno** [comment]
I fixed all merge conflicts with the caused by release `0.35.0`. Given that the `once` macro error is solved, I will open this pull request for review again

**Comment by jaemk** [comment]
Looks good to me!

**Pull request merged**
